# Плохой compose-файл: намеренно содержит bad practices для лабораторной работы
services:
  main:
    build:
      context: .
      dockerfile: bad.Dockerfile
    container_name: lab2-bad-main
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "hardcoded_secret_in_compose"
      APP_NAME: "Bad main service"
    user: root
    privileged: true
    networks:
      - shared_net

  storage:
    build:
      context: .
      dockerfile: bad.Dockerfile
    container_name: lab2-bad-storage
    ports:
      - "8001:8000"
    environment:
      SECRET_KEY: "hardcoded_secret_in_compose"
      APP_NAME: "Bad storage service"
    user: root
    privileged: true
    networks:
      - shared_net

networks:
  shared_net:
    driver: bridge
